export const MW_BEHAVIOR_SWITCHES: string[] = [
  '__NOTOC__', '__FORCETOC__', '__TOC__', '__NOEDITSECTION__', '__NEWSECTIONLINK__', '__NONEWSECTIONLINK__',
  '__NOGALLERY__', '__HIDDENCAT__', '__EXPECTUNUSEDCATEGORY__', '__NOCONTENTCONVERT__', '__NOCC__', '__NOTITLECONVERT__', '__NOTC__',
  '__START__', '__END__', '__INDEX__', '__NOINDEX__', '__STATICREDIRECT__', '__NOGLOBAL__', '__DISAMBIG__',
  '__EXPECTED_UNCONNECTED_PAGE__',
];

export const MW_VARIABLES: Set<string> = new Set<string>([
  'CURRENTYEAR', 'CURRENTMONTH', 'CURRENTMONTH1', 'CURRENTMONTHNAME', 'CURRENTMONTHNAMEGEN', 'CURRENTMONTHABBREV',
  'CURRENTDAY', 'CURRENTDAY2', 'CURRENTDOW', 'CURRENTDAYNAME', 'CURRENTTIME', 'CURRENTHOUR', 'CURRENTWEEK', 'CURRENTTIMESTAMP',

  'LOCALYEAR', 'LOCALMONTH', 'LOCALMONTH1', 'LOCALMONTHNAME', 'LOCALMONTHNAMEGEN', 'LOCALMONTHABBREV',
  'LOCALDAY', 'LOCALDAY2', 'LOCALDOW', 'LOCALDAYNAME', 'LOCALTIME', 'LOCALHOUR', 'LOCALWEEK', 'LOCALTIMESTAMP',

  'SITENAME', 'SERVER', 'SERVERNAME', 'DIRMARK', 'DIRECTIONMARK', 'SCRIPTPATH', 'STYLEPATH', 'CURRENTVERSION',
  'CONTENTLANGUAGE', 'CONTENTLANG', 'PAGEID', 'PAGELANGUAGE', 'PROTECTIONLEVEL', 'PROTECTIONEXPIRY', 'CASCADINGSOURCES',
  'REVISIONID', 'REVISIONDAY', 'REVISIONDAY2', 'REVISIONMONTH', 'REVISIONMONTH1', 'REVISIONYEAR', 'REVISIONTIMESTAMP',
  'REVISIONUSER', 'REVISIONSIZE',
  'DISPLAYTITLE', 'DEFAULTSORT', 'DEFAULTSORTKEY', 'DEFAULTCATEGORYSORT',
  'PAGESINCATEGORY', 'PAGESINCAT', 'NUMBERINGROUP', 'NUMINGROUP', 'PAGESINNS', 'PAGESINNAMESPACE',
  'NUMBEROFPAGES', 'NUMBEROFARTICLES', 'NUMBEROFFILES', 'NUMBEROFEDITS', 'NUMBEROFVIEWS', 'NUMBEROFUSERS', 'NUMBEROFADMINS',
  'NUMBEROFACTIVEUSERS',
  'FULLPAGENAME', 'PAGENAME', 'BASEPAGENAME', 'ROOTPAGENAME', 'SUBPAGENAME', 'SUBJECTPAGENAME', 'ARTICLEPAGENAME',
  'TALKPAGENAME',
  'FULLPAGENAMEE', 'PAGENAMEE', 'BASEPAGENAMEE', 'ROOTPAGENAMEE', 'SUBPAGENAMEE', 'SUBJECTPAGENAMEE', 'ARTICLEPAGENAMEE',
  'TALKPAGENAMEE',
  'NAMESPACE', 'NAMESPACENUMBER', 'SUBJECTSPACE', 'ARTICLESPACE', 'TALKSPACE',
  'NAMESPACEE', 'SUBJECTSPACEE', 'ARTICLESPACEE', 'TALKSPACEE',
  '!', '=',
]);

export const MW_URL_SCHEMES = [
  'bitcoin:', 'ftp://', 'ftps://', 'geo:', 'git://', 'mvn:', 'gopher://', 'http://',
  'https://', 'irc://', 'ircs://', 'irc6://', 'magnet:', 'mailto:', 'mms://', 'news:', 'itms:', 'market:', 'spotify:', 'steam:',
  'nntp://', 'redis://', 'sftp://', 'sip:', 'sips:', 'sms:', 'ssh://', 'fax:', 'fm:', 'hcp://', 'im:', 'imap://', 'teamspeak://',
  'svn://', 'tel:', 'callto:', 'skype:', 'zoommtg://', 'zoomus://', 'telnet://', 'urn:', 'worldwind://', 'xmpp:', 'slack://', '//',
];