export type AvatarBaseType = 'Knight' | 'Mage' | 'Priest' | 'Rogue' | 'Shaman' | 'Warlock' | 'Warrior';

export type AvatarDamageType = 'Fire' | 'Ice' | 'Imaginary' | 'Physical' | 'Quantum' | 'Thunder' | 'Wind';

export interface AvatarConfig {
  AIPath: string,
  ActionAvatarHeadIconPath: string,
  AdventurePlayerId: number,
  AssistBgOffset: number[],
  AssistOffset: number[],
  AvatarBaseType: AvatarBaseType,
  AvatarCutinBgImgPath: string,
  AvatarCutinFrontImgPath: string,
  AvatarCutinImgPath: string,
  AvatarCutinIntroTextMapHash: number,
  AvatarDescTextMapHash: number,
  AvatarDropOffset: number[],
  AvatarFullNameTextMapHash: number,
  AvatarGachaResultImgPath: string,
  AvatarId: number,
  AvatarMiniIconPath: string,
  AvatarNameText: string,
  AvatarNameTextMapHash: number,
  AvatarSelfShowOffset: number[],
  AvatarSideIconPath: string,
  AvatarTrialOffset: number[],
  AvatarVOTag: string,
  DamageType: AvatarDamageType,
  DamageTypeResistance: never,
  DefaultAvatarHeadIconPath: string,
  DefaultAvatarModelPath: string,
  ExpGroup: number,
  JsonPath: string,
  ManikinJsonPath: string,
  MaxPromotion: number,
  MaxRank: number,
  PlayerCardOffset: number[],
  RankIdList: number[],
  Rarity: string,
  Release: boolean,
  RewardList: { ItemId: number, ItemNum: number }[],
  RewardListMax: { ItemId: number, ItemNum: number }[],
  SPNeedValue: number,
  SideAvatarHeadIconPath: string,
  SkillList: number[],
  SkilltreePrefabPath: string,
  UIAvatarModelPath: string,
  UltraSkillCutInPrefabPath: string,
  WaitingAvatarHeadIconPath: string,
}
