export interface AvatarExcelConfigData {
  Id: number,
  QualityType: string,
  NameText: string,
  NameTextMapHash: number,
  DescText: string,
  DescTextMapHash: number,
  InfoDescText: string,
  InfoDescTextMapHash: number,
  InitialWeapon: number,
  WeaponType: string,
  BodyType: string,
  IconName: string,
  ImageName: string,
  SideIconName: string,
}

export interface AvatarFlycloakExcelConfigData {
  FlycloakId: number,
  NameText: string,
  DescText: string,
  NameTextMapHash: number,
  DescTextMapHash: number,
  PrefabPath: string,
  JsonName: string,
  Icon: string,
  MaterialId: number
}

export interface AvatarCostumeExcelConfigData {
  SkinId: number,
  IndexId: number,
  NameTextMapHash: number,
  DescTextMapHash: number,
  ItemId: number,
  CharacterId: number,
  JsonName: string,
  PrefabPathHash: string,
  PrefabRemotePathHash: string,
  PrefabNpcPathHash: string,
  PrefabManekinPathHash: string,
  Quality: number,
  FrontIconName: string,
  SideIconName: string,
  ImageNameHash: string,
  NameText: string,
  DescText: string,
  IsDefaultUnlock: boolean,
  Hide: boolean,
  AnimatorConfigPathHash: string,
  ControllerPathHash: string,
  ControllerRemotePathHash: string,
  IsDefault: boolean,
  DomesticHideInArtPreview: boolean,
}