export interface ConfigCondition<T extends string = string> {
  Type?: T,
  Param?: (string|number)[]
  Count?: string,
  ParamStr?: string,
}

export interface NpcExcelConfigData {
  Id: number,
  NameTextMapHash: number,
  NameText: string,

  JsonName: string,
  SpecialType: string,
  BodyType: string,
  Alias: string,

  HasMove: boolean,
  HasAudio: boolean,
  IsDaily: boolean,
  Invisiable: boolean,
  DisableShowName: boolean,
  UseDynBone: boolean,
  SkipInitClosetToGround: boolean,
  IsActivityDailyNpc: boolean,

  BillboardType: string,
  BillboardIcon: string,

  CampId: number,
  FirstMetId: number,
  UniqueBodyId: number,

  ScriptDataPath: string,
  PrefabPathHash: string,
  TemplateEmotionPath: string,
  AnimatorConfigPathHash: string,
  JsonPathHash: string,
  LuaDataPath: string,
  LuaDataIndex: number,
  OKJNGNPPCBP: string,
  JMJLKENBJEA: number,
  BHDMIMPGPOI: number[],
}

export interface DungeonExcelConfigData {
  Id: number,
  NameTextMapHash: number,
  NameText: string,
  DisplayNameTextMapHash: number,
  DisplayNameText: string,
  DescTextMapHash: number,
  DescText: string,
  Type: string,
  SceneId: number,
  InvolveType: string,
  ShowLevel: number,
  LimitLevel: number,
  LevelRevise: number,
  PassCond: number,
  ReviveMaxCount: number,
  DayEnterCount: number,
  EnterCostItems: any[]
  PassRewardPreviewId: number,
  SettleCountdownTime: number,
  FailSettleCountdownTime: number,
  QuitSettleCountdownTime: number,
  SettleShows: string[],
  ForbiddenRestart: boolean,
  SettleUIType: string,
  RecommendElementTypes: string[],
  RecommendTips: any[],
  LevelConfigMap: any,
  PreviewMonsterList: number[],
  GearDescTextMapHash: number,
  CityId: number,
  EntryPicPath: string,
  StateType: string,
  FactorPic: string,
  FactorIcon: string,
  AvatarLimitType: number,
  IsDynamicLevel: boolean,
  SubType: string,
  SerialId: number,
  FirstPassRewardPreviewId: number,
  PassJumpDungeon: number,
  DontShowPushTips: boolean,
  PlayType: string,
  EventInterval: number,
  ReviveIntervalTime: number,
  StatueCostId: number,
  StatueCostCount: number,
  StatueDrop: number,
}

export interface AchievementExcelConfigData {
  GoalId: number,
  OrderId: number,

  Id: number,
  TitleText: string,
  TitleTextEN: string,
  TitleTextMapHash: number,
  DescText: string,
  DescTextMapHash: number,
  Ps5TitleText: string,
  Ps5TitleTextMapHash: number,

  PreStageAchievementId: number,
  FinishRewardId: number,

  IsDeleteWatcherAfterFinish: boolean,
  TriggerConfig: object,
  Progress: number,
  Ps4GroupId: number,
  Ps5GroupId: number,
  Ttype: string,
  PsTrophyId: string,
  Ps4TrophyId: string,
  Ps5TrophyId: string,
  Icon: string,
  IsShow: string,
  IsDisuse: boolean,
  ProgressShowType: string,
}


export interface AchievementGoalExcelConfigData {
  Id: number,
  OrderId: number,
  NameText: string,
  NameTextMapHash: number,
  IconPath: string,
  FinishRewardId: number,
}
