export interface ConfigCondition<T extends string = string> {
  Type?: T,
  Param?: (string|number)[]
  Count?: string,
  ParamStr?: string,
}

export interface NpcExcelConfigData {
  JsonName: string,
  Alias: string,
  ScriptDataPath: string,
  LuaDataPath: string,
  DyePart: string,
  BillboardIcon: string,
  TemplateEmotionPath: string,
  Id: number,
  NameText?: string,
  NameTextMapHash: number,
  PrefabPathHashSuffix: number,
  PrefabPathHashPre: number,
  CampId: number,
  LODPatternName: string,
  BodyType?: string,
}

export interface AvatarExcelConfigData {
  Id: number,
  QualityType: string,
  NameText: string,
  NameTextMapHash: number,
  DescText: string,
  DescTextMapHash: number,
  InfoDescText: string,
  InfoDescTextMapHash: number,
  InitialWeapon: number,
  WeaponType: string,
  BodyType: string,
  IconName: string,
  ImageName: string,
  SideIconName: string,
}

export interface DungeonExcelConfigData {
  Id: number,
  NameTextMapHash: number,
  NameText: string,
  DisplayNameTextMapHash: number,
  DisplayNameText: string,
  DescTextMapHash: number,
  DescText: string,
  Type: string,
  SceneId: number,
  InvolveType: string,
  ShowLevel: number,
  LimitLevel: number,
  LevelRevise: number,
  PassCond: number,
  ReviveMaxCount: number,
  DayEnterCount: number,
  EnterCostItems: any[]
  PassRewardPreviewId: number,
  SettleCountdownTime: number,
  FailSettleCountdownTime: number,
  QuitSettleCountdownTime: number,
  SettleShows: string[],
  ForbiddenRestart: boolean,
  SettleUIType: string,
  RecommendElementTypes: string[],
  RecommendTips: any[],
  LevelConfigMap: any,
  PreviewMonsterList: number[],
  GearDescTextMapHash: number,
  CityId: number,
  EntryPicPath: string,
  StateType: string,
  FactorPic: string,
  FactorIcon: string,
  AvatarLimitType: number,
  IsDynamicLevel: boolean,
  SubType: string,
  SerialId: number,
  FirstPassRewardPreviewId: number,
  PassJumpDungeon: number,
  DontShowPushTips: boolean,
  PlayType: string,
  EventInterval: number,
  ReviveIntervalTime: number,
  StatueCostId: number,
  StatueCostCount: number,
  StatueDrop: number,
}

export interface AchievementExcelConfigData {
  GoalId: number,
  OrderId: number,

  Id: number,
  TitleText: string,
  TitleTextEN: string,
  TitleTextMapHash: number,
  DescText: string,
  DescTextMapHash: number,
  Ps5TitleText: string,
  Ps5TitleTextMapHash: number,

  PreStageAchievementId: number,
  FinishRewardId: number,

  IsDeleteWatcherAfterFinish: boolean,
  TriggerConfig: object,
  Progress: number,
  Ps4GroupId: number,
  Ps5GroupId: number,
  Ttype: string,
  PsTrophyId: string,
  Ps4TrophyId: string,
  Ps5TrophyId: string,
  Icon: string,
  IsShow: string,
  IsDisuse: boolean,
  ProgressShowType: string,
}


export interface AchievementGoalExcelConfigData {
  Id: number,
  OrderId: number,
  NameText: string,
  NameTextMapHash: number,
  IconPath: string,
  FinishRewardId: number,
}
