export interface ConditionGroup {
  Id: number,
  GroupId: number[],
  HintText: string,
  HintTextValue: string,
  Relation: 0 | 1 | 10,
  Conditions: Condition[],
}

export interface Condition {
  Id: number,
  Type: ConditionType,
  IsClient: boolean,

  Description: string,
  DescriptionText: string,

  NeedNum: number,
  LimitParams: {
    Key: ConditionLimitParamsKey,
    Op?: ConditionOp,
    Value: string
  }[],
  LimitParamsOpe?: { Key: string, Value: ConditionOp }[],
}

export type ConditionOp = '<' | '<=' | '>' | '>=';

export type ConditionType =
  'ActivatePhantomFettles'        |
  'BattleRoleIsNot'               |
  'BattleRoleWeaponType'          |
  'BossRushScore'                 |
  'CalabashLevel'                 |
  'CapturePhantom'                |
  'CheckAccountSettingOpen'       |
  'CheckActivityOpen'             |
  'CheckAnyRoleFullPhantom'       |
  'CheckCharacterTagByEvent'      |
  'CheckCharacterTagNotByEvent'   |
  'CheckClientQuest'              |
  'CheckCreatureTag'              |
  'CheckCurWorldLevel'            |
  'CheckCurWorldLevelOp'          |
  'CheckDailyCounter'             |
  'CheckDirection'                |
  'CheckDis'                      |
  'CheckDrop'                     |
  'CheckDungeonFinished'          |
  'CheckDungeonId'                |
  'CheckEnemyBuff'                |
  'CheckEnemyTag'                 |
  'CheckEquippedPhantom'          |
  'CheckExplorationLevel'         |
  'CheckExploreSkill'             |
  'CheckFightEnergyBall'          |
  'CheckFightEnergyBar'           |
  'CheckFormationAnyRoleDead'     |
  'CheckGuideStatus'              |
  'CheckHasFirstPhantomAtPosition'|
  'CheckHasUnlockAffixInBossRush' |
  'CheckInputAction'              |
  'CheckInstanceState'            |
  'CheckIsMulti'                  |
  'CheckLevel'                    |
  'CheckLevelOp'                  |
  'CheckLevelPlayNodeState'       |
  'CheckOnCostInsufficient'       |
  'CheckOnTreasureBoxOpen'        |
  'CheckOriginWorldLevel'         |
  'CheckRangeByPbDataId'          |
  'CheckRogueCanUnlockSkill'      |
  'CheckRogueTerm'                |
  'CheckRoleLevel'                |
  'CheckSelfEntityCommonTag'      |
  'CheckShop'                     |
  'CheckStrikeInfo'               |
  'CheckTeamRoleCouldLevelUp'     |
  'CheckTeamWeaponCouldLevelUp'   |
  'CheckTeleportStatus'           |
  'CheckTeleportTypeUnlock'       |
  'CheckUIOpen'                   |
  'CheckUIState'                  |
  'CheckVisionIntensifyTabOpen'   |
  'CheckWorldMapSecondaryUiOpened'|
  'ClientCalabashLevel'           |
  'ComboTeachingState'            |
  'CookingLevelUp'                |
  'CostItem'                      |
  'CostItemBagType'               |
  'CreateAdvice'                  |
  'DailyQuestGroupCompleteTimes'  |
  'Detection'                     |
  'DistanceLess'                  |
  'DragonPoolLevel'               |
  'DragonPoolState'               |
  'DrawCardCompleteTimes'         |
  'EntityDie'                     |
  'EntityDieByType'               |
  'EntityInteractById'            |
  'EntityInteractByType'          |
  'EntityStateByBpType'           |
  'EntityStateByBpTypeOnline'     |
  'EntityStateById'               |
  'FightWithMonster'              |
  'FinishGuideStepByEvent'        |
  'FinishInst'                    |
  'FinishRogueInst'               |
  'FinishRogueInstDiffRole'       |
  'FinishRogueInstPopularEntrie'  |
  'FirstGetRole'                  |
  'FirstRoleBreakthrough'         |
  'FoodProcess'                   |
  'FunctionUnlock'                |
  'GetInstanceScore'              |
  'GetItem'                       |
  'GetNewItem'                    |
  'GetWhichRole'                  |
  'HarmonyQte'                    |
  'HarvestScore'                  |
  'HpLowerThan'                   |
  'InstACE'                       |
  'ItemCheck'                     |
  'KillMonster'                   |
  'LevelConditionCheckBuff'       |
  'LevelPlayComplete'             |
  'LevelPlayTypeComplete'         |
  'LongShanRwdCount'              |
  'MoveStateCheck'                |
  'NewQuestState'                 |
  'NewQuestStepState'             |
  'OnBulletCalculate'             |
  'OnDamageCalculate'             |
  'OnDeathCalculate'              |
  'OnPlayerUseSkill'              |
  'OnSkillEnable'                 |
  'OnTakingPhoto'                 |
  'OnViewClose'                   |
  'OpenLevelPlay'                 |
  'OpenTreasureBox'               |
  'ParkourActivityComplete'       |
  'PassLordGymDifficulty'         |
  'PawnInRange'                   |
  'PhantomIdentify'               |
  'PhantomMaxLevel'               |
  'PhantomTargetLevel'            |
  'Photograph'                    |
  'PlayerRevive'                  |
  'QuestState'                    |
  'QuestStepState'                |
  'Record'                        |
  'ReduceWorldLevel'              |
  'RoleAddBuff'                   |
  'RoleBreach'                    |
  'RoleFavorLevel'                |
  'RoleLevel'                     |
  'RoleResonance'                 |
  'RoleSkillAllNodeMax'           |
  'RoleSkillTargetLevel'          |
  'RoleTargetLevel'               |
  'SceneGamePlayStatus'           |
  'SceneStepState'                |
  'SelfGameplayTagCheck'          |
  'SelfTagCheck'                  |
  'SlotOfCurrentRole'             |
  'SomeMonsterKill'               |
  'SomeQuestComplete'             |
  'StartShootTarget'              |
  'StrengthenPhantomMax'          |
  'Synthesis'                     |
  'SynthesisLevelUp'              |
  'TakeSceneItem'                 |
  'TargetTagCheck'                |
  'TeamRoleLevel'                 |
  'TeamWeaponLevel'               |
  'TotalFinishInstTimes'          |
  'TowerLimitedPass'              |
  'TowerPerfectPass'              |
  'TriggerInterative'             |
  'TriggerTeleport'               |
  'TurnTableBigRewardCount'       |
  'UseSkill'                      |
  'VarDefineString'               |
  'WeaponBreakthrough'            ;

export type ConditionLimitParamsKey =
  'Action'            |
  'ActivityId'        |
  'AnimalType'        |
  'AreaId'            |
  'AreaIds'           |
  'AttackerBulletID'  |
  'AttackerID'        |
  'Available'         |
  'BagType'           |
  'BeCounter'         |
  'BpType'            |
  'Breach'            |
  'BreachLevel'       |
  'BuffId'            |
  'BulletID'          |
  'CalculateType'     |
  'CheckTag'          |
  'CheckValue'        |
  'CheckWay'          |
  'Climb'             |
  'CollectType'       |
  'Count'             |
  'CountType'         |
  'CounterType'       |
  'CreatureGen'       |
  'DQGroupId'         |
  'DQTimes'           |
  'DeBuffCount'       |
  'DeBuffs'           |
  'Difficulty'        |
  'Dir'               |
  'Distance'          |
  'DragonPoolId'      |
  'DropId'            |
  'Element'           |
  'ElementId'         |
  'ElementType'       |
  'EndTargetTag'      |
  'EntityCommonTag'   |
  'EntityConfigId'    |
  'EntityMainType'    |
  'EntryCount'        |
  'ExtraParam'        |
  'Finish'            |
  'FinishInst'        |
  'Floor'             |
  'FormulaType'       |
  'FunctionId'        |
  'GamePlayTag'       |
  'Glide'             |
  'GroupIndex'        |
  'GuideGroupId'      |
  'Hp'                |
  'Id'                |
  'InstSubType'       |
  'InstanceId'        |
  'InterativeId'      |
  'IsCritical'        |
  'IsFull'            |
  'IsOpen'            |
  'IsPlayer'          |
  'ItemID'            |
  'ItemId'            |
  'ItemShowType'      |
  'ItemType'          |
  'Kind'              |
  'Level'             |
  'LevelPlayId'       |
  'MatchAll'          |
  'MaxScoreCount'     |
  'MonsterId'         |
  'MonsterType'       |
  'Negative'          |
  'NewQuestId'        |
  'NodeId'            |
  'Online'            |
  'Op'                |
  'Other'             |
  'PawnId'            |
  'PbDataId'          |
  'PhantomId'         |
  'Position'          |
  'Quality'           |
  'QuestID'           |
  'QuestNodeId'       |
  'QuestType'         |
  'Rate'              |
  'Reason'            |
  'RecordId'          |
  'Result'            |
  'RogueGainId'       |
  'RoleCount'         |
  'RoleId'            |
  'Second'            |
  'ShopId'            |
  'ShopItemId'        |
  'SkillId'           |
  'SkillType'         |
  'Slot'              |
  'StartTarget'       |
  'State'             |
  'Status'            |
  'StepGroupId'       |
  'StepID'            |
  'Striker'           |
  'StrikerDir'        |
  'SubType'           |
  'Swim'              |
  'Tag'               |
  'TargetOldLifeRate' |
  'TargetType'        |
  'TeleportId'        |
  'TeleportType'      |
  'Type'              |
  'UIName'            |
  'UIState'           |
  'VDName'            |
  'VDValueString'     |
  'ValueCount1'       |
  'ValueCount2'       |
  'VictimID'          |
  'WeaponType'        ;

